language: generic
python:
  - "3.7"
services:
  - docker

before_script:
  - make install-deps

script:
  - make test
  - docker build -t project42:${TRAVIS_COMMIT} .
  - docker run project42:${TRAVIS_COMMIT} pytest
