name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag manoelhc/project42:$(date +%s) --tag manoelhc/project42:latest
    - name: Test Docker iamge
      run: docker run manoelhc/project42:latest pytest
    - name: Push Docker iamge
      uses: docker/build-push-action@v1
      with:
        repository: manoelhc/project45
        registry: docker.pkg.github.com
