name: Python Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7.8"
          architecture: "x64"
      - name: Install dependencies
        run: make install-deps
      - name: Run tests
        run: make test
